library flutter_nfc_p2p;

export 'src/models/nfc_event.dart';
export 'src/flutter_nfc_p2p_platform_interface.dart'
    show FlutterNfcP2pPlatform;

import 'src/flutter_nfc_p2p_method_channel.dart';
import 'src/flutter_nfc_p2p_platform_interface.dart';
import 'src/models/nfc_event.dart';

/// Entry point for the flutter_nfc_p2p plugin.
///
/// This class is strictly headless. It exposes a [Stream<NfcEvent>] that the
/// host application subscribes to, and imperative methods to control HCE
/// (sender) and reader (receiver) modes.
///
/// **Typical sender flow:**
/// ```dart
/// await FlutterNfcP2p.startHce(token: mySecureToken);
/// FlutterNfcP2p.eventStream.listen((event) {
///   if (event is HceStartedEvent) showReadyUI();
///   if (event is NfcErrorEvent) showError(event.message);
/// });
/// ```
///
/// **Typical receiver flow:**
/// ```dart
/// await FlutterNfcP2p.startReader();
/// FlutterNfcP2p.eventStream.listen((event) {
///   if (event is NfcListeningEvent) showWaitingUI();
///   if (event is NfcTokenReceivedEvent) sendToServer(event.token);
///   if (event is NfcErrorEvent) showError(event.message);
/// });
/// ```
class FlutterNfcP2p {
  FlutterNfcP2p._();

  static FlutterNfcP2pPlatform get _platform {
    // Register the default MethodChannel implementation the first time this
    // getter is called. Tests can replace it by setting
    // FlutterNfcP2pPlatform.instance = mock before calling any FlutterNfcP2p
    // method — the hasInstance guard preserves that override.
    if (!FlutterNfcP2pPlatform.hasInstance) {
      FlutterNfcP2pPlatform.instance = MethodChannelFlutterNfcP2p();
    }
    return FlutterNfcP2pPlatform.instance;
  }

  /// Broadcast stream of [NfcEvent]s from both HCE and reader mode.
  ///
  /// The stream is a broadcast stream — multiple listeners are supported.
  /// It never closes; events are pushed by the native layer on demand.
  static Stream<NfcEvent> get eventStream => _platform.eventStream;

  /// Start HCE on the **sender** (payer) device.
  ///
  /// [token] should be a short-lived, cryptographically secure string
  /// generated by your backend. The token is embedded in the APDU response.
  ///
  /// [notificationTitle] and [notificationBody] set the text shown in the
  /// system notification when a tap is detected while the app is backgrounded.
  /// Defaults to "Payment Sent" / "Tap to open" if omitted.
  ///
  /// Throws [UnsupportedError] if the device does not support HCE.
  static Future<void> startHce({
    required String token,
    String? notificationTitle,
    String? notificationBody,
  }) =>
      _platform.startHce(
        token,
        notificationTitle: notificationTitle,
        notificationBody: notificationBody,
      );

  /// Stop the active HCE service on the sender device.
  static Future<void> stopHce() => _platform.stopHce();

  /// Enable NFC reader mode on the **receiver** (merchant) device.
  ///
  /// Immediately emits [NfcListeningEvent]. When a sender taps, emits
  /// [NfcTokenReceivedEvent] with the extracted token.
  ///
  /// Throws [UnsupportedError] if NFC reader is not available.
  static Future<void> startReader() => _platform.startReader();

  /// Disable NFC reader mode.
  static Future<void> stopReader() => _platform.stopReader();

  /// Returns true if NFC is supported and enabled on this device.
  static Future<bool> isNfcAvailable() => _platform.isNfcAvailable();

  /// Returns true if this plugin's HCE service is the system-default
  /// for its AID category on this device.
  static Future<bool> isDefaultHceService() => _platform.isDefaultHceService();

  /// Marks this plugin's HCE service as the foreground-preferred service
  /// while the current activity is in the foreground.
  ///
  /// Call this when the HCE sender screen becomes visible so the system
  /// routes NFC taps to this app without a disambiguation dialog.
  /// Works on both Pixel (AOSP) and Samsung devices.
  ///
  /// Returns true if the system accepted the preference.
  static Future<bool> setPreferredHceService() =>
      _platform.setPreferredHceService();

  /// Clears the foreground-preferred service previously set by
  /// [setPreferredHceService]. Call this when the HCE sender screen is hidden.
  static Future<void> clearPreferredHceService() =>
      _platform.clearPreferredHceService();

  /// Opens the system NFC "change default" settings screen so the user can
  /// permanently select this app as the default contactless payment app.
  ///
  /// Uses [CardEmulation.ACTION_CHANGE_DEFAULT] which is handled by both
  /// the AOSP NFC settings (Pixel) and Samsung's NFC settings app.
  static Future<void> openHceDefaultSettings() =>
      _platform.openHceDefaultSettings();
}
